version: 3

tasks:
    default:
        desc: List all tasks
        cmds:
            - task --list-all

    install:
        cmds:
            - bun install

    install-dist:
        dir: dist
        cmds:
            - bun install

    clean:
        cmds:
            - bun del dist
            - bun del out
            #- rm -rf node_modules

    clean-modules:
        cmds:
            - bun del ./**/node_modules

    clean-dist:
        cmds:
            - bun del dist

    fixtures:
        cmds:
            - curl -o fixtures/api.json https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/examples/v2.0/json/petstore.json
            - npx biome format --write fixtures/api.json

    run:
        cmds:
            - npx del out/petsClientFull.ts
            - node --experimental-strip-types src/bin.ts fixtures/api.json out -n petsClientFull
            - npx biome format --write out/petsClientFull.ts

    run-short:
        cmds:
            - npx del out/petsClientShort.ts
            - node --experimental-strip-types src/bin.ts fixtures/api.json out -n petsClientShort -m short
            - npx biome format --write out/petsClientShort.ts

    run-dist:
        cmds:
            - npx del out/petsClientFull.ts
            - node dist/bin.js fixtures/api.json out -n petsClientFull
            - npx biome format --write out/petsClientFull.ts

    run-short-dist:
        cmds:
            - npx del out/petsClientShort.ts
            - node dist/bin.js fixtures/api.json out -n petsClientShort -m short
            - npx biome format --write out/petsClientShort.ts

    ncu:
        cmds:
            - ncu
            - ncu --packageFile package.json.dist

    build:
        cmds:
            - npx del dist
            - npx esbuild src/_templates/client/full/index.ts --bundle --platform=node --outdir=dist/_templates/client/full/
            - npx esbuild src/_templates/client/short/index.ts --bundle --platform=node --outdir=dist/_templates/client/short/
            - npx esbuild src/.hygen.js --bundle --platform=node --outdir=dist
            - npx esbuild src/bin.ts --bundle --platform=node --outdir=dist
            - cp src/_templates/client/full/new-client.ejs.t dist/_templates/client/full/new-client.ejs.t 
            - cp src/_templates/client/short/new-client.ejs.t dist/_templates/client/short/new-client.ejs.t 
            - cp src/opsSchemaTemplate.hbs dist/_templates/client/full/opsSchemaTemplate.hbs
            - cp src/template.hbs dist/_templates/client/full/template.hbs
            - cp src/opsSchemaTemplate.hbs dist/_templates/client/short/opsSchemaTemplate.hbs
            - cp src/template.hbs dist/_templates/client/short/template.hbs
            - cp package.json.dist dist/package.json
            - cp .npmignore dist/.npmignore

    publish:
        dir: dist
        cmds:
            - task: build
            - npm publish --access=public
            
